### ISSUE TITLE
[v5.0.0~v5.4.0] "設定ダイアログ画面サイズ固定化プラグイン" を使用した際の描画乱れ

### ISSUE THREAD

**Issue by MTTK03** [hebiiro/AviUtl-Plugin-DarkenWindow#4]
いつも使いやすいプラグインをありがとうございます！

私の環境では amate さんの [設定ダイアログ画面サイズ固定化プラグイン v2.6](https://github.com/amate/PropertyWindowFixerPlugin) を使用しているのですが、
黒窓 v5.0.0~v5.4.0 を導入すると、以下のように `設定ダイアログ` に描画の乱れが発生してしまいます。

<img width="373" alt="スクリーンショット 2022-05-19 211047" src="https://user-images.githubusercontent.com/74399503/169290246-796b0f90-f6a4-479e-a38a-005dbfead984.png">

黒窓 v4.2.0 以前だと発生しないようでして...
可能であればご対応頂きたいです！
よろしくお願いします！

**Comment by hebiiro** [comment]
5.4.1 で修正しました。

**Comment by MTTK03** [comment]
<img width="374" alt="スクリーンショット 2022-05-19 231519" src="https://user-images.githubusercontent.com/74399503/169315362-2afdb1d7-1c30-49ab-9e26-772c9da831c0.png">

問題なく描画されるようになりました！
素早いご対応、ありがとうございました！
