### ISSUE TITLE
[v6.2.0 , v6.2.1] rikky_moduleでの色設定ダイアログの描画に遅延が発生する

### ISSUE THREAD

**Issue by nea-c** [hebiiro/AviUtl-Plugin-DarkenWindow#5]
rikky_moduleのcolordialog、colordialogCS関数を利用した際に設定ダイアログに生えるボタンを押すと
以下の画像のような状況が発生します。

また、描画が完了するまでの間、このウインドウは操作を反映しません。

### ※
* rikky_moduleのその他設定ダイアログにボタン等を生やすもの
* `v6.2.0` `v6.2.1` 以外のバージョン

でのデバッグはしておりませんこと、ご了承ください。

![image](https://user-images.githubusercontent.com/45559303/172032839-9403d35f-83c6-4540-90da-05537f74a77b.png)

## 動作環境
Windows 11 Pro / version 21H2 / OS Build 22000.675

**Comment by hebiiro** [comment]
その現象が再現可能なスクリプトの名前を教えてください。

**Comment by nea-c** [comment]
私の[個別カラー](https://github.com/nea-c/AviUtl-Scripts/tree/master/個別カラー)で起きます
他スクリプトでの検証はしてないのでわかりませんが、数が多いからとかありえますかね？

黒窓非導入状態では起きないため導入状態でrikky_module関連のさらなる検証が必要かもしれません

- 追記
このスクリプトの設定ダイアログ内のテキストボックスにマウスカーソルを合わせるとテキストボックスの枠がちらつくことがあります

- 追記2
拡張編集の環境設定内にあるテキストボックスでもちらつきを確認できました

**Comment by hebiiro** [comment]
黒窓なしの aviutl_dark.exe でも発生するので対応は難しいです。

**Comment by nea-c** [comment]
マジですか...

**Comment by hebiiro** [comment]
https://github.com/hebiiro/AviUtl-Plugin-script_sort_patch/releases/tag/2.0.0 で改善しませんでしたか？

**Comment by nea-c** [comment]
改善しました！
ありがとうございます！！！！
