### ISSUE TITLE
「アニメーション効果」を追加するほど設定ダイアログが重くなる

### ISSUE THREAD

**Issue by Tsut-ps** [hebiiro/AviUtl-Plugin-DarkenWindow#6]
## 概要
以下の環境下で、拡張機能の設定ダイアログの描画がかなり重くなる現象が発生しました。
・スクリプトをそこそこ入れている
・黒窓（v8.0.0）を入れている
・アニメーション効果を入れる

### Twitter(X)のスレッド
https://twitter.com/Tsut_ps/status/1721780757071626371

## 検証
- Layer A/B に 「アニメーション効果」を4つ入れる
- Layer C/D に「斜めクリッピング」を4つ入れる（比較用）

### 黒窓 導入なし

https://github.com/hebiiro/AviUtl-Plugin-DarkenWindow/assets/73014392/a7390321-d962-464f-8bcd-49f01500732e

### 黒窓 導入あり

https://github.com/hebiiro/AviUtl-Plugin-DarkenWindow/assets/73014392/d098fd75-cb0f-47a9-a455-8d1f759fff9f

### 平均表示秒数

|  | アニメーション効果x4 | 斜めクリッピングx4 |
| ------------- | ------------- | ------------- |
| 導入なし | 0.52s | 0.21s |
| 導入あり | **1.38s** | 0.38s |

表示が2～3倍程度時間がかかっているようです。

### 他にも試して改善が見られたこと
スクリプトの数をいくつか間引くことでも、改善が見られました。
https://twitter.com/Tsut_ps/status/1721931493617090945

**Comment by Tsut-ps** [comment]
導入なし/ありの動画がまさかの真逆だったので正しく差し替えました、申し訳ないです。

**Comment by hebiiro** [comment]
黒窓はWindowsのビジュアルスタイルというのをフック(横取り)して描画を変更するんですが、テストしてみたらこのビジュアルスタイルを有効にした時点で重かったです。フックをしなくても重いのでこれはWindowsの仕様かもしれないです。テストの仕方としては、[黒窓 7.3.0](https://github.com/hebiiro/AviUtl-Plugin-DarkenWindow/releases/tag/7.3.0)でaviutl_dark.exeを作ってDarkenWindow.aulをPluginsフォルダに入れずにaviutl_dark.exeで同じ検証をすると多分重いと感じると思います。

**Comment by Tsut-ps** [comment]
検証ありがとうございます。

> テストの仕方としては、[黒窓 7.3.0](https://github.com/hebiiro/AviUtl-Plugin-DarkenWindow/releases/tag/7.3.0)でaviutl_dark.exeを作ってDarkenWindow.aulをPluginsフォルダに入れずにaviutl_dark.exeで同じ検証をすると多分重いと感じると思います。

こちら同様に再現しました。なるほど、Windowsのビジュアルスタイルという機能自体が重たいのですね……。

（余談かもです：
> [ハイ コントラスト モードはビジュアル スタイルを操作するように変更されています。](https://learn.microsoft.com/ja-jp/windows/win32/controls/themes-overview)
> [11 Windowsでは、ハイ コントラスト モードはコントラスト テーマで処理されます。](https://support.microsoft.com/ja-jp/windows/windows-%E3%81%A7%E3%83%8F%E3%82%A4-%E3%82%B3%E3%83%B3%E3%83%88%E3%83%A9%E3%82%B9%E3%83%88-%E3%83%A2%E3%83%BC%E3%83%89%E3%82%92%E3%82%AA%E3%83%B3%E3%81%AB%E3%81%99%E3%82%8B-909e9d89-a0f9-a3a9-b993-7a6dcee85025)

Windowsのハイコントラスト モードでもビジュアルスタイルが使われるとあって、Windows 11でコントラスト テーマを変えてみたところ、こちらは何故か再現しませんでした。Win 11では違う何かが使われているんですかね……？）

Windowsの仕様の可能性が高そうなので、導入スクリプトを少なくするなどで対応しようと思います🙇
